okta:
  oauth2:
    issuer: https://dev-542348.okta.com/oauth2/default
    #issuer: https://authq.securebanklogin.com/oauth2/default

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${okta.oauth2.issuer}/v1/keys
